language: go
sudo: false

os:
  - linux
  - osx

matrix:
  include:
    - go: "1.11"

before_install:
  - go get github.com/mattn/goveralls
  - go mod vendor

script:
  - go get -t -v ./...
  - go test ./...
  - $GOPATH/bin/goveralls -service=travis-ci
